version: "3.8"

services:
  archaeologist:
    image: ghcr.io/sarcophagus-org/sarcophagus-v2-archaeologist-service:latest
    network_mode: "host"
    restart: on-failure
    env_file:
      - ./.env
    command:
      - /bin/bash
      - -c
      - |
        npm run peer-id-gen
        NODE_NO_WARNINGS=1 npm run cli start
    volumes:
      - type: bind
        source: ./peer-id.json
        target: /home/node/app/peer-id.json
    stdin_open: true
    tty: true
    environment:
      FORCE_COLOR: 1
      NODE_NO_WARNINGS: 1
      CHAIN_ID: 5
